### ISSUE TITLE
Support PostgreSQL 9.5

### ISSUE THREAD

**Issue by mc-soi** [credativ/informix_fdw#10]
I hacked a few functions to compile on 9.5 alpha2
"It compiles."  C is not my native language, so this may have some stupid bugs in it.
https://gist.github.com/mc-soi/6b4a504bc1393c4ba9f4

This was helpful when researching the API change:
http://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=1a8a4e5cde2b7755e11bde2ea7897bd650622d3e#patch14

**Comment by psoo** [comment]
Many thanks, i'll look into it.

**Comment by mc-soi** [comment]
Thanks!  You might have to add a few "#if (PG_VERSION_NUM >= 90500)"'s so that the code will continue to compile with older versions.

**Comment by psoo** [comment]
Finally arrived. See 9edfa29cb2cb2edd58433585fd96c77a57776e3b. There finally was more work needed to get PostgreSQL 9.5 fully supported, so i've decided not to reuse your patch.
