### ISSUE TITLE
fdw performance

### ISSUE THREAD

**Issue by apollo13** [credativ/informix_fdw#14]
Issuing a `select count(*) from table` results in massive traffic according to wireshark, which would suggest that the execution of the query is not really pushed down to the server? Is that expected or am I missing something?

**Comment by psoo** [comment]
Yeah, this is how the current FDW API works. The aggregate is performed on the local side. Each row needs to be fetched from the remote server. There's currently massive work in progress to make the FDW API better, e.g. upcoming JOIN, DML and sort order pushdown in 9.6. But for aggregate pushdown we aren't there yet...
