### ISSUE TITLE
Support PostgreSQL 9.6

### ISSUE THREAD

**Issue by mc-soi** [credativ/informix_fdw#17]
In order to compile with PostgreSQL 9.6, I had to make the same change as shown in this diff for www_fdw:
https://github.com/robe2/www_fdw/commit/91db3fb1f8f178f476ee2508b890ea8f3812cbcb#diff-c253b5a69422b106657b1e306862c098R631

After compiling and installing, I found that it worked fine for SELECTs.  I have not tested more than that.

**Comment by psoo** [comment]
I've just pushed REL0_4_0 with various fixes and support for PostgreSQL 9.6.
