### ISSUE TITLE
Client sdk no longer available. 

### ISSUE THREAD

**Issue by hunkeelin** [credativ/informix_fdw#20]
http://www-01.ibm.com/software/data/informix/tools/csdk/

the above got redirected. I had to go to fix center and select the software. 

https://www-945.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm~Information%20Management&product=ibm/Information+Management/Informix+Client+Software+Development+Kit&release=All&platform=Linux+32-bit,x86&function=textSearch&text=linux

However, IMB require licenses to download the sdk. Is there a place where you host the sdk so users can download off it? 

Thanks

**Comment by JCTTTTTTT** [comment]
Hello hunkeelin,

You can download the SDK for free from this link _(Plan to create a free IBM account before you can access the downloads)_ :
[https://www-01.ibm.com/marketing/iwm/iwm/web/preLogin.do?source=ifxdl&S_PKG=410FC8dewin&lang=en_US](url)
And select the last client sdk Dev.
for exemple : 
> Informix Client SDK Developer Edition for Linux x86, 32-bit
> Version  4.10.UC9DE
or
> Informix Client SDK Developer Edition for Linux x86_64, 64-bit
> Version  4.10.FC9DE 

best,
JC

**Comment by rockallite** [comment]
> Hello hunkeelin,
> 
> You can download the SDK for free from this link _(Plan to create a free IBM account before you can access the downloads)_ :
> https://www-01.ibm.com/marketing/iwm/iwm/web/preLogin.do?source=ifxdl&S_PKG=410FC8dewin&lang=en_US
> And select the last client sdk Dev.
> for exemple :
> 
> > Informix Client SDK Developer Edition for Linux x86, 32-bit
> > Version  4.10.UC9DE
> > or
> > Informix Client SDK Developer Edition for Linux x86_64, 64-bit
> > Version  4.10.FC9DE
> 
> best,
> JC

Even that link is not available now...

**Comment by dlopes7** [comment]
That link is still available, I just downloaded it right now. IBM makes it so hard to find and download software on their website it always boggles my mind.
