### ISSUE TITLE
multiple definition error on Ubuntu 22.04.1 LTS

### ISSUE THREAD

**Issue by herwigg** [credativ/informix_fdw#35]
Hi,

When I try to compile informix_fdw on Ubuntu 22.04 I get an error during make:
The error occurs using PGBIN=/usr/lib/postgresql/15/bin/ but as well with /usr/lib/postgresql/14/bin/
Follozing variables are set:
export USE_PGXS=1;
export PG_CONFIG=$PGBIN/pg_config
export INFORMIXSERVER=csdk
export INFORMIXDIR=/usr/ifx-csdk-current
export PATH=$INFORMIXDIR/bin:$PATH
export TERMCAP=$INFORMIXDIR/etc/termcap
#export ONCONFIG=onconfig.$INFORMIXSERVER
export DBDATE=Y4MD0
export DBMONEY=BF,
export NODEFDAC=yes
export DB_LOCALE=nl_be.8859-1
export CLIENT_LOCALE=$DB_LOCALE
#export LDR_CNTRL=USERREGS
export FET_BUF_SIZE=65536

if [ -z "$LD_LIBRARY_PATH" ]
then
  LD_LIBRARY_PATH=$INFORMIXDIR/lib:$INFORMIXDIR/lib/esql
else
  LD_LIBRARY_PATH=$INFORMIXDIR/lib:$INFORMIXDIR/lib/esql:$LD_LIBRARY_PATH
fi
export LD_LIBRARY_PATH
and /usr/ifx-csdk-current is a symnoplic link to /opt/IBM/informix/CSDK.4.50.FC7
The error is:
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -shared -o ifx_fdw.so ifx_connection.o ifx_conncache.o ifx_utils.o ifx_conv.o ifx_fdw.o -L/usr/lib/x86_64-linux-gnu  -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -L/usr/lib/llvm-14/lib  -Wl,--as-needed -Wl,--no-as-needed -lifsql -lifasf -lifgen -lifos -lifgls -lpthread -lm -ldl -lcrypt /usr/ifx-csdk-current/lib/esql/checkapi.o -lifglx -Wl,--as-needed -L/usr/ifx-csdk-current/lib/ -L/usr/ifx-csdk-current/lib/esql
/usr/bin/ld: ifx_fdw.o (symbol from plugin): in function `ifxCache':
(.text+0x0): multiple definition of `ifxCache'; ifx_conncache.o (symbol from plugin):(.text+0x0): first defined here
/usr/bin/ld: ifx_fdw.o (symbol from plugin): in function `ifxCache':
(.text+0x0): multiple definition of `IfxCacheIsInitialized'; ifx_conncache.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [/usr/lib/postgresql/15/lib/pgxs/src/makefiles/../../src/Makefile.shlib:293: ifx_fdw.so] Error 1

any idea how to resolve this ?

**Comment by psoo** [comment]
Hi @herwigg ,

Are you using the latest master branch? I am referring to this specific commit:

https://github.com/credativ/informix_fdw/commit/b8f721ba2656b0685af1f42b83be41e981a13e51

I haven't done a new release tarball yet, since there are other important code changes pending.

**Comment by herwigg** [comment]
Hi, I was on a holiday. I use indeed the latest master branch. You are saying I should just clone the informix_fdw as it contains the latest code changes and try to compile with this version ?

**Comment by herwigg** [comment]
Hi , I did a git clone and it compiled on my Ubuntu 22.04 server. Did not do any tests yet. Is there a planning for a new release ? Is this a matter of weeks or longer ?

**Comment by psoo** [comment]
I hope i can get my hands on it, soon.

**Comment by psoo** [comment]
Should be fixed as of commit b8f721ba2656b0685af1f42b83be41e981a13e51, thus closed.
